export const OPEN_NEW_FILM_MODAL = 'OPEN_NEW_FILM_MODAL';
export const CLOSE_NEW_FILM_MODAL = 'CLOSE_NEW_FILM_MODAL';
export const OPEN_NEW_FILM_FROM_FILE_MODAL = 'OPEN_NEW_FILM_FORM_FILE_MODAL';
export const CLOSE_NEW_FILM_FROM_FILE_MODAL = 'CLOSE_NEW_FILM_FROM_FILE_MODAL';
export const OPEN_DELETE_FILM_MODAL = 'OPEN_DELETE_FILM_MODAL';
export const CLOSE_DELETE_FILM_MODAL = 'CLOSE_DELETE_FILM_MODAL';